name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # Executa sempre que houver push na branch main
  workflow_dispatch: # Permite execução manual pela aba Actions

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout seu código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm' # Ou 'yarn' / 'pnpm'

      - name: Instalar dependências
        run: npm install

      - name: Build do Projeto Astro
        run: npm run build

      - name: Upload do artefato para o Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # Pasta de saída definida no astro.config.mjs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4